### ISSUE TITLE
Argo CD basic example failed creating basic-example

### ISSUE THREAD

**Issue by AlyIbrahim** [redhat-cop/declarative-openshift#30]
I am testing the creation of ArgoCD instance on OCP 4.5, and I got this error:
`The ArgoCD "example-argocd" is invalid: spec.server.route: Invalid value: "boolean": spec.server.route in body must be of type object: "boolean"`

It turned out from the CD that the CRD is  looking for an object instead of a boolean on the new operator version.

**Comment by sabre1041** [comment]
@AlyIbrahim can this be closed as the associated PR has been merged?

**Comment by AlyIbrahim** [comment]
Yep, Closing it !
